sudo: required

services:
  - docker

before_install:
  - docker build -t jorgensta/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jorgensta/react-test yarn test -- --coverage

after_success:
  - docker build -t jorgensta/m-client ./client
  - docker build -t jorgensta/m-nginx ./nginx
  - docker build -t jorgensta/m-server ./server
  - docker build -t jorgensta/m-worker ./worker
  # first login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to dockerhub

  - docker push jorgensta/m-client
  - docker push jorgensta/m-nginx
  - docker push jorgensta/m-server
  - docker push jorgensta/m-worker

